### PR TITLE
adding skip "button" to android tv

### PR DESCRIPTION
**Pull request by dredstone1**
addig skip "button" to android tv, by waiting until the user paussed the video while its in intro and then skip, it will also send a message at the beginning of the intro to skip the intro, like a button.

### CODE REVIEW

**Comment by dredstone1** [comment]
this is the idea. there is some Glitz but its because its running on emulator, its not happening in the tv

https://github.com/user-attachments/assets/897a759c-0630-44bd-b8b2-f2ffe0015180

**Comment by dredstone1** [comment]
there is any way to set the amount of time the message is going to show up, or its a set amount of time?

**Comment by AbandonedCart** [comment]
This should probably be secondary to the UI for #208, since it seems to be a workaround to emulate a skip button. It should also be tested in Kodi and other implementations to see if it would be a viable workaround for all of them or just Android TV.

**Comment by jumoog** [comment]
Sorry, but this is a bad idea. Once we have the Segment API, we should get official client support.

**Comment by dredstone1** [comment]
yes, i will test it in kodi(i never used kodi so i dont know how it handle messages.
i want to say that this is like you said just a workaround and it will be until they finally add skip button.
maybe i will call this feature "skip on pause" or i will called it a "skip button", i still dont know.
for know i much prefer this implementation than the auto skip one, i still dont know it will

**Comment by AbandonedCart** [comment]
> Deleted the comment including the video... as it was still visible in the history.

I was giving you a chance to see if ;)

**Comment by dredstone1** [comment]
no need

**Comment by dredstone1** [comment]
i still going to use it myself, until Segment will be ready.

**Comment by AbandonedCart** [comment]
That's the joy of open-source.

**Comment by jumoog** [comment]
A big problem I have from time to time is that I can't read the session for the Android TV app. This means I can't see the play state and I can't send messages or seek commands.

**Pull request closed without merging**
