### PR TITLE
Merge Scheduled Tasks

### PR DESCRIPTION
**Pull request by rlauu**
Merges the functionality of the Detect Intro Task and Detect Credit Task into a single, unified Detect Intro and Credits Task. Simplifies workflow and reduces code duplication.

If there were reasons for separation, please comment.

### CODE REVIEW

**Comment by jumoog** [comment]
True. Maybe we should merge `credits.xml` and `intros.xml` as well?

**Comment by AbandonedCart** [comment]
Some people run them individually, such as me

**Comment by jumoog** [comment]
sorry :(

**Comment by AbandonedCart** [comment]
It may be worth doing a rebase so it's not a bunch of reverting revert commits

**Comment by rlauu** [comment]
Yes, but I still don't see the benefit of having separate tasks over the merged task other than for testing purposes.

**Comment by AbandonedCart** [comment]
What's the benefit of merging them?

**Comment by AbandonedCart** [comment]
If they were identical tasks running for tv and movies separately, I would completely agree. They are different tasks running for different purposes with some overlap.  You honestly can't find a way to reduced duplication without completely merging them?

**Comment by AbandonedCart** [comment]
Ideally, the user should be able to run one task individually, but running both tasks at the same time should be possible. The filter for what to scan should apply to automatic scan only. That provides the user with the maximum number of configuration options.

**Comment by jumoog** [comment]
I will think about it during the holidays. But I think the previous author was not quite finished with the credit addon before he archived the repo and therefore there are 2 different tasks for him to test.

**Comment by AbandonedCart** [comment]
He had basically just thrown it in there, but it uses a separate set of analyzers that are more or less obsolete. I think the other problem is all of these changes being super rushed.

**Comment by AbandonedCart** [comment]
I fixed the code and merged it. I'll just clean it up later.

**Comment by jumoog** [comment]
We work at the speed we want/need. There is no need to rush. I really appreciate your work.  If you see things differently, we can talk about everything. I don't always know what the right way is and I'm open to suggestions.

**Comment by AbandonedCart** [comment]
I have no problem with working fast, but it seems like there is only specific usage scenario in all of these changes. The problem with this becoming the successor to the plugin almost everyone knew is that you get stuck either considering everyone or telling them to get lost.

**Comment by jumoog** [comment]
I am happy to fix bugs or accept reasonable changes. It is first and foremost our plugin. If people prefer another plugin they are welcome to use it. I just need a plugin to skip the intro. Success is not important to me.

**Comment by AbandonedCart** [comment]
It still needs to be cleaned up, but https://github.com/jumoog/intro-skipper/commit/e7f56624d15c639a8f6f43ebfdb1d79e8342ac34 is what I was trying to explain. It's possible to have BOTH a merged task that is optimized, but also still give people the option to do partial scans.

**Comment by jumoog** [comment]
Tomorrow I'll see if it's possible to trigger the tasks as part of the automatic mode. That way people will see in the dashboard that the task is currently running.

**Comment by AbandonedCart** [comment]
It would definitely help to know it's already running.

**Comment by AbandonedCart** [comment]
Wanted to take a second and apologize to both of you. I got involved in a project with some toxic people and then got pretty sick and misdirected some of my stress here. I am hugely grateful for the contributions @rlauuzo and got a little too overwhelmed to show it properly.

**Comment by jumoog** [comment]
Dont worry @AbandonedCart 😊I'll do some tests tomorrow and then we should release a new version. Or is there something we should add first?

**Comment by AbandonedCart** [comment]
That sounds good. I haven't had any issues so far.

**Pull request closed without merging**
