### PR TITLE
Make auto skip work with Kodi

### PR DESCRIPTION
**Pull request by qwerty12**
(Just curious, is there any reason why the released binaries are built with the Debug release configuration? I saved a whopping 5 KB by building with Release)

Thanks for all the work on continuing Intro Skipper 🫡

### CODE REVIEW

**Comment by AbandonedCart** [comment]
This would also break Android TV, even if it did fix Kodi

**Comment by qwerty12** [comment]
As the test currently is (`||`), the auto skipping functionality fails to work on both the Jellyfin Android TV client as well as Kodi for me. Changing it to `&&` fixed things for me in both clients.

Unless I'm being dopey, from what I can see using `||` is causing both `session.Client != "Android TV"` and `session.Client != "Kodi"` tests to be evaluated and `session.Client` can't be both. Short circuiting rules should work as expected with `&&`: if `session.Client` is "Android TV", the rest won't get checked and the loop won't be `continue`d and in the case session.Client is "Kodi", the first test fails but not the second and thus `continue` won't be hit

**Comment by AbandonedCart** [comment]
See https://github.com/jumoog/intro-skipper/pull/208

**Comment by AbandonedCart** [comment]
I had to read the original changes a few times because it is *very* backwards. It probably was a typo, but it would likely be replaced by having a UI to actually set which clients skip. I'm not sure if it was left that way to intentionally not do anything or because the typo was overlooked by merging it ahead of the UI.

Either way, your correction makes more sense based on the original purpose of #208

**Comment by jumoog** [comment]
haha omg thank you! yes that was a stupid mistake

**Pull request merged**
