### PR TITLE
Add user settings to configure skip behavior on client site (alternative to #261)

### PR DESCRIPTION
**Pull request by rlauuzo**

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Honestly, adding this and then going back to clean up the configuration page with a multiple choice instead of many individual checkboxes seems like the most efficient route.

**Comment by AbandonedCart** [comment]
There's no option for review to vote against a PR, but that's where I stand on the other one. I don't know how much luck you'll have trying to explain the issues with it.

**Comment by jumoog** [comment]
From my point of view we do not need options. If you watch in pip it will skip for you. If you dont want that, dont go in pip. But that is just my opinion. Feel free to choose whatever you prefer.

**Comment by AbandonedCart** [comment]
I feel like skipping in pip should be tied to auto. If you skip with a button and care that much, jump back to the video, skip, then send it back. I don't see any reason that if pip doesn't provide the ability to include buttons, that any plugin should have to compensate for it.

**Comment by AbandonedCart** [comment]
The plugin and picture in picture have been around quite a while. It just seems like this would have come up at least once before. I don't think it'll see much use, but changing skip options by client would be nice. That's the value I see in it.

**Comment by dredstone1** [comment]
I think that there is no need for this pr, because it's already in #261.

**Comment by AbandonedCart** [comment]
> I think that there is no need for this pr, because it's already in #261.

It’s an alternative, as stated in the title.

**Comment by rlauuzo** [comment]
I've tested it, and it's working on desktop, mobile, and TV without any issues so far. However, it might be better to wait until [this pull request](https://github.com/jumoog/intro-skipper/pull/208) is merged to avoid any conflicts between server-side and client-side auto-skip.

**Comment by dredstone1** [comment]
> > I think that there is no need for this pr, because it's already in #261.
> 
> It’s an alternative, as stated in the title.

I know that is an alternative, it's the same as #261, and it missing the dashboard configuration, I think it will be better if he will add the last fixes into #261

**Comment by AbandonedCart** [comment]
> I know that is an alternative, it's the same as #261, and it missing the dashboard configuration, I think it will be better if he will add the last fixes into #261

I think leaving out the dashboard was the point.

**Comment by AbandonedCart** [comment]
> However, it might be better to wait until [this pull request](https://github.com/jumoog/intro-skipper/pull/208) is merged to avoid any conflicts between server-side and client-side auto-skip.

That's where I feel a server side pip option would fit, too. It's the same scenario. The button won't work, but the user may want it. That's what I was originally suggesting in #206

**Review by AbandonedCart — APPROVED** [review]

**Comment by dredstone1** [comment]
if you add the option to show the button or not show the button, shouldn't you remove this option from the dashboard configuration?

**Comment by AbandonedCart** [comment]
This is separate from the dashboard.

**Comment by dredstone1** [comment]
I know, he add an option that do the same thing as an option in the dashboard

**Comment by AbandonedCart** [comment]
Yes. Separately. The dashboard is not being touched.

**Comment by dredstone1** [comment]
OK, I just think that it can be confusing to have the same option twice, but do as you feel

**Comment by AbandonedCart** [comment]
There's no reason we need to keep having the same conversation over and over, so I locked comments to just contributors.

**Comment by AbandonedCart** [comment]
At some point, we will have to address the fact that this will always override the server setting, even when the server setting is changed. It can be reset by clearing document storage. It's a client setting that won't carry between clients. All the eccentricities. That is assuming it's not just temporary.

**Comment by rlauuzo** [comment]
Alternatively, I could move it into the playback settings, where Jellyfin stores its persistent client settings.

**Comment by AbandonedCart** [comment]
I like that more than local storage. Local storage feels a bit like cache in that it could disappear at any moment without necessarily being intentional.

**Comment by rlauuzo** [comment]
It would still use the browser's local storage, which is also utilized by Jellyfin.

**Comment by AbandonedCart** [comment]
I guess it would just be semantics at that point

**Review by jumoog — APPROVED** [review]

**Comment by AbandonedCart** [comment]
Are we clear to move forward on this?

**Comment by jumoog** [comment]
lgtm we can merge it

**Pull request merged**
