### PR TITLE
Inject Timestamps into Episode Details

### PR DESCRIPTION
**Pull request by rlauuzo**
Implement Timestamps on Episode Details Page

352654402-165d023e-57e1-467f-8363-fee4a8c9f121
352654460-30e0e400-99c6-4fc6-b79f-898a6f2ad2b5

### CODE REVIEW

**Comment by rlauuzo** [comment]
This can be tested using Tampermonkey and requires the plugin version from [this pull request](https://github.com/jumoog/intro-skipper/pull/223). Also, replace `[protocol]://[url]` with your Jellyfin URL.

```
// ==UserScript==
// @name         Introskipper Injector
// @namespace    http://tampermonkey.net/
// @version      2024-07-27
// @description  Adds Introskipper Timestamps in Jellyfin.
// @author       introskipper
// @match        [protocal]://[url]/web/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=greasyfork.org
// @grant        none
// ==/UserScript==
(function() {
    'use strict';
    console.log("Introskipper Data Injector Script loaded");

    document.addEventListener('viewshow', onViewShow);

    function onViewShow() {
        const location = window.location.hash;
        console.debug("Current: " + location);
        if (location.startsWith('#/details')) {
            console.debug('Attempting to inject skipper data');
            injectDetailsPage();
        }
    }

    async function injectDetailsPage() {
        const visibleItemDetailPage = document.querySelector('div#itemDetailPage:not(.hide)');
        const detailPageContent = visibleItemDetailPage && visibleItemDetailPage.querySelector('.detailPageContent');
        if (!detailPageContent || detailPageContent.querySelector('#skipperCollapsible')) {
            console.debug('DetailPageContent not found or skipper data already injected');
            return;
        }
        const episodeId = new URLSearchParams(window.location.hash.split('?')[1]).get('id');
        if (!episodeId) {
            console.debug('Episode ID not found in URL');
            return;
        }
        const skipperData = await secureFetch(`Episode/${episodeId}/Timestamps`);
        if (!skipperData || Object.keys(skipperData).length === 0) {
            console.debug('No skipper data found for this episode');
            return;
        }
        detailPageContent.appendChild(createSkipperDataElement(episodeId, skipperData));
        console.debug('Skipper Data injected');
    }

    function createSkipperDataElement(episodeId, skipperData) {
        const skipperCollapsible = document.createElement('div');
        skipperCollapsible.id = 'skipperCollapsible';
        skipperCollapsible.className = 'verticalSection detailVerticalSection verticalSection-extrabottompadding emby-scroller-container';
        const Introduction = skipperData.Introduction || {};
        const Credits = skipperData.Credits || {};
        const formatTime = (time) => time !== undefined ? `${Number(time).toFixed(2)}\u202Fs` : 'N/A';
        skipperCollapsible.innerHTML = `
            <div class="content-primary">
                <h2 class="sectionTitle sectionTitle-cards">Intro Skipper</h2>
                <div class="itemsContainer vertical-list">
                    <div class="listItem listItem-border" style="padding-right:2em">
                        <div class="listItemBody">
                            ${Introduction.IntroStart !== undefined ? `<h3 class="listItemBodyText">Intro Start: ${formatTime(Introduction.IntroStart)}, Intro End: ${formatTime(Introduction.IntroEnd)}</h3>` : ''}
                            ${Credits.IntroStart !== undefined ? `<h3 class="listItemBodyText">Credits Start: ${formatTime(Credits.IntroStart)}, Credits End: ${formatTime(Credits.IntroEnd)}</h3>` : ''}
                            <div class="listItemBodyText secondary" style="font-size: smaller; margin-top: 8px;">Episode ID: ${episodeId}</div>
                        </div>
                        <button is="emby-button" type="button" class="raised" id="editSkipperData"><span>Edit Timestamps</span></button>
                    </div>
                </div>
            </div>
        `;
        skipperCollapsible.querySelector('#editSkipperData').addEventListener('click', () => openEditDialog(episodeId, skipperData));
        return skipperCollapsible;
    }

    function openEditDialog(episodeId, skipperData) {
        console.debug('Edit button clicked for episode:', episodeId);
        const dialog = document.createElement('div');
        dialog.innerHTML = `
            <div class="dialogBackdrop dialogBackdropOpened"></div>
            <div class="dialogContainer">
                <div class="focuscontainer dialog dialog-fixedSize dialog-small formDialog opened" data-history="true" modal="modal" data-autofocus="true" data-removeonclose="true" style="animation: 180ms ease-out both scaleup;">
                    <div class="formDialogHeader" style="display: flex; justify-content: space-between; align-items: center;">
                        <h3 class="formDialogHeaderTitle">Edit Timestamps</h3>
                        <button is="paper-icon-button-light" class="btnCancel btnClose autoSize paper-icon-button-light" tabindex="-1" title="Close">
                            <span class="material-icons close" aria-hidden="true"></span>
                        </button>
                    </div>
                    <div class="formDialogContent smoothScrollY" style="padding-top:2em">
                        <form class="editTimestampsForm dialogContentInner dialog-content-centered">
                            ${createInput('Intro Start', 'introStart', skipperData.Introduction ? skipperData.Introduction.IntroStart : 0)}
                            ${createInput('Intro End', 'introEnd', skipperData.Introduction ? skipperData.Introduction.IntroEnd : 0)}
                            ${createInput('Credits Start', 'creditsStart', skipperData.Credits ? skipperData.Credits.IntroStart : 0)}
                            ${createInput('Credits End', 'creditsEnd', skipperData.Credits ? skipperData.Credits.IntroEnd : 0)}
                        </form>
                    </div>
                    <div class="formDialogFooter">
                        <button is="emby-button" type="button" class="raised button-submit block btnSave formDialogFooterItem emby-button">
                            <span>Save</span>
                        </button>
                    </div>
                </div>
            </div>
        `;
        document.body.appendChild(dialog);
        dialog.querySelector('.btnSave').addEventListener('click', async () => {
            const newTimestamps = {
                Introduction: {
                    IntroStart: parseFloat(document.getElementById('introStart').value),
                    IntroEnd: parseFloat(document.getElementById('introEnd').value)
                },
                Credits: {
                    IntroStart: parseFloat(document.getElementById('creditsStart').value),
                    IntroEnd: parseFloat(document.getElementById('creditsEnd').value)
                }
            };
            const response = await secureFetch(`Episode/${episodeId}/Timestamps`, "POST", JSON.stringify(newTimestamps));
            if (response.ok) {
                console.debug('Timestamps updated successfully');
                const updatedSkipperData = await secureFetch(`Episode/${episodeId}/Timestamps`);
                const detailPageContent = document.querySelector('.detailPageContent');
                const oldSkipperCollapsible = document.getElementById('skipperCollapsible');
                if (oldSkipperCollapsible) {
                    detailPageContent.replaceChild(createSkipperDataElement(episodeId, updatedSkipperData), oldSkipperCollapsible);
                }
            } else {
                console.error('Failed to update timestamps:', response.status, response.statusText);
                alert('Failed to update timestamps. Please try again.');
            }
            document.body.removeChild(dialog);
        });
        dialog.querySelector('.btnCancel').addEventListener('click', () => document.body.removeChild(dialog));
    }

    function createInput(label, id, value = 0) {
        return `
            <div class="inputContainer">
                <label class="inputLabel inputLabelUnfocused" for="${id}">${label}</label>
                <input id="${id}" type="number" step="any" min="0" class="emby-input" value="${value}">
            </div>
        `;
    }

    async function secureFetch(url, method = "GET", body = null) {
        url = new URL(url, ApiClient.serverAddress());
        const headers = { "Authorization": `MediaBrowser Token=${ApiClient.accessToken()}` };
        if (method === "POST") headers["Content-Type"] = "application/json";
        const response = await fetch(url, { method, headers, body });
        if (!response.ok) throw new Error(`Expected status 200 from ${url}, but got ${response.status}`);
        return response.json();
    }
})();
```

**Comment by rlauuzo** [comment]
Here's an alternative version:

```
// ==UserScript==
// @name         Introskipper Injector
// @namespace    http://tampermonkey.net/
// @version      2024-07-27
// @description  Adds Introskipper Timestamps in Jellyfin.
// @author       introskipper
// @match        [protocal]://[url]/web/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=greasyfork.org
// @grant        none
// ==/UserScript==
(function() {
    'use strict';
    console.log("Introskipper Data Injector Script loaded");

    /**Setup Event Listeners */
    document.addEventListener('viewshow', viewShowEvent);

    // Mutation Observer
    const observer = new MutationObserver(handleMutation);

    // Only observe when on details
    observer.disconnect();

    function viewShowEvent(){
        const location = window.location.hash;
        console.debug("Current: " + location);
        if (location.startsWith('#/details')){
            console.debug('Connecting Observer');
            observer.observe(document.body, {childList: true, subtree: true});
        }
        else{
            console.debug('Disconnecting Observer');
            observer.disconnect();
        }
    }

    async function handleMutation() {
        observer.disconnect();
        try {
            console.debug("Attempting to inject skipper data");
            const metadataFormFields = document.querySelector('.metadataFormFields');
            if (!metadataFormFields || metadataFormFields.querySelector('.introskipperSection')) {
                console.debug('metadataFormFields not found or already injected, will try again on next mutation');
                return;
            }
            // Extract the episode ID from the URL
            const episodeId = new URLSearchParams(window.location.hash.split('?')[1]).get('id');
            if (!episodeId) {
                console.debug('Episode ID not found in URL');
                return;
            }
            console.debug('Episode ID:', episodeId);
            // Fetch skipper data from the server
            const skipperData = await secureFetch("Episode/" + episodeId + "/Timestamps");
            if (!skipperData || Object.keys(skipperData).length === 0) {
                console.debug('No skipper data found for this episode');
                return;
            }
            // Add the skipper fields to metadataFormFields
            addSkipperFields(metadataFormFields, skipperData);
            attachSaveListener(episodeId, skipperData);
        } finally {
            observer.observe(document.body, {childList: true, subtree: true});
        }
    }

    function addSkipperFields(metadataFormFields, skipperData) {
        const skipperFields = document.createElement('div');
        skipperFields.className = 'detailSection introskipperSection';
        skipperFields.innerHTML = `
            <h2>Intro Skipper</h2>
            <div class="introskipperTimestamps editorFieldset">
            <div class="inputContainer">
            <label class="inputLabel inputLabelUnfocused" for="introStart">Intro Start</label>
            <input type="number" id="introStart" step="any" min="0" class="emby-input" value="${skipperData.Introduction ? skipperData.Introduction.IntroStart : 0}">
            </div>
            <div class="inputContainer">
            <label class="inputLabel inputLabelUnfocused" for="introEnd">Intro End</label>
            <input type="number" id="introEnd" step="any" min="0" class="emby-input" value="${skipperData.Introduction ? skipperData.Introduction.IntroEnd : 0}">
            </div>
            <div class="inputContainer">
            <label class="inputLabel inputLabelUnfocused" for="creditsStart">Credits Start</label>
            <input type="number" id="creditsStart" step="any" min="0" class="emby-input" value="${skipperData.Credits ? skipperData.Credits.IntroStart : 0}">
            </div>
            <div class="inputContainer">
            <label class="inputLabel inputLabelUnfocused" for="creditsEnd">Credits End</label>
            <input type="number" id="creditsEnd" step="any" min="0" class="emby-input" value="${skipperData.Credits ? skipperData.Credits.IntroEnd : 0}">
            </div>
            </div>
        `;
        metadataFormFields.appendChild(skipperFields);
    }

    function attachSaveListener(episodeId, skipperData) {
        const saveButton = document.querySelector('.formDialogFooter .btnSave');
        if (saveButton) {
            saveButton.addEventListener('click', () => saveSkipperData(episodeId, skipperData));
        } else {
            console.debug('Save button not found');
        }
    }

    async function saveSkipperData(episodeId, skipperData) {
        const newTimestamps = {
            Introduction: {
                IntroStart: parseFloat(document.getElementById('introStart').value),
                IntroEnd: parseFloat(document.getElementById('introEnd').value)
            },
            Credits: {
                IntroStart: parseFloat(document.getElementById('creditsStart').value),
                IntroEnd: parseFloat(document.getElementById('creditsEnd').value)
            }
        };
        if (Object.entries(newTimestamps).every(([section, times]) =>
            Object.entries(times).every(([key, value]) =>
                Math.abs(value - (skipperData[section]?.[key] || 0)) < Number.EPSILON
            )
        )) {
            console.log('Timestamps have not changed, skipping update');
            return;
        }
        const response = await secureFetch("Episode/" + episodeId + "/Timestamps", "POST", JSON.stringify(newTimestamps));
        if (response.ok) {
            console.log('Timestamps updated successfully');
        } else {
            console.error('Failed to update timestamps:', response.status, response.statusText);
            alert('Failed to update timestamps. Please try again.');
        }
    }

    async function secureFetch(url, method = "GET", body = null) {
        url = new URL(url, ApiClient.serverAddress());
        const headers = { "Authorization": `MediaBrowser Token=${ApiClient.accessToken()}` };
        if (method === "POST") headers["Content-Type"] = "application/json";
        const response = await fetch(url, { method, headers, body });
        if (!response.ok) throw new Error(`Expected status 200 from ${url}, but got ${response.status}`);
        return response.json();
    }
})();
```

**Comment by jumoog** [comment]
I prefer the first. Maybe its better to use a time input?

**Comment by rlauuzo** [comment]
This is now ready for testing! Lets you edit timestamps directly from the episode metadata editor.

**Comment by jumoog** [comment]
works great

**Comment by AbandonedCart** [comment]
If we can do that, would removing the plugin version of this make sense? Not the code, but at least disabling the UI and instead providing instructions on how to use this method. It would also solve the need to make that section more visual.

**Comment by jumoog** [comment]
> If we can do that, would removing the plugin options version of the editor make sense? Not the code, but at least disabling the UI and instead providing instructions on how to use this method. It would also solve the need to make that section more visual.

Yes, that might make sense.

**Comment by AbandonedCart** [comment]
The fingerprint chart always seemed like more a novelty for those interested in how the data is used, but at the cost of having to load two episodes every time I wanted to edit one.

**Comment by jumoog** [comment]
But if our script cannot be injected, there is no other way to change the times. 🤔

**Comment by AbandonedCart** [comment]
If the script can't be injected, it won't work anyway.

**Pull request merged**
