### PR TITLE
Update Css

### PR DESCRIPTION
**Pull request by rlauuzo**

### CODE REVIEW

**Comment by rlauuzo** [comment]
grafik
grafik

Allows for custom accent color and border radius.

**Comment by AbandonedCart** [comment]
That looks good!

**Comment by rlauuzo** [comment]
Should we use the emby-button instead?

**Comment by jumoog** [comment]
What's the difference?

**Comment by rlauuzo** [comment]
emby-button is general purpose button for Jellyfin. paper-icon-button-light is for displaying icons.  You can test it here. https://github.com/rlauuzo/intro-skipper/releases/tag/10.9%2Fvtest

**Comment by AbandonedCart** [comment]
I think the paper one was originally used for the secondary effects. It’s a weird design in general, so a button meant to be a button will almost definitely be better for the purpose.

**Comment by jumoog** [comment]
Better matches UI style

**Comment by rlauuzo** [comment]
Ready, if no one else has feedback.

**Comment by AbandonedCart** [comment]
Nothing looks out of place, so I've got nothing.

**Comment by jumoog** [comment]
Lgtm

**Comment by jumoog** [comment]
ready?

**Comment by rlauuzo** [comment]
Yeah, but if you merge, you'll probably have to change `document.querySelector("#skipIntro")` to `document.querySelector("#skipIntro .emby-button")` in https://github.com/jumoog/intro-skipper/pull/170

**Comment by barrio5** [comment]
I like the styling of the buttons and I would like the same style for the skip notification messages, so they all share the same design priciples. Is that possible?

**Comment by jumoog** [comment]
This has nothing to do with this plugin. What you are looking for is called jellyfin theme. Please look at the [Jellyfin Forum](https://forum.jellyfin.org/f-themes-styles) or [List on Githbub](https://github.com/awesome-jellyfin/awesome-jellyfin/blob/main/THEMES.md)

**Pull request merged**
