### PR TITLE
add option to get storage usage per library

### PR DESCRIPTION
**Pull request by jumoog**

### CODE REVIEW

**Comment by jumoog** [comment]
add a new option to get storage usage per library
grafik

**Comment by jumoog** [comment]
I'm still surprised that Jellyfin doesn't have it somewhere already.

**Comment by AbandonedCart** [comment]
I'm not sure I understand the relevance. It's useful information that I would think Jellyfin itself should include, as you said, but is anyone really going to think to go looking for it here?

**Comment by jumoog** [comment]
It has no relevance for this plugin but I often need this information for myself 😂

**Comment by AbandonedCart** [comment]
Good enough.

**Review by rlauuzo — APPROVED** [review]

**Pull request merged**
