### PR TITLE
Removed non custom UI disclaimer

### PR DESCRIPTION
**Pull request by JPVenson**
Custom Button can be enabled just fine, so remove disclaimer

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Good catch. I have a feeling a lot of the documentation needs a rewrite, but this one is pretty important.

**Comment by JPVenson** [comment]
To be honest, not my catch someone asked in the jellyfin chat about it and i saw it was wrong^^

**Comment by AbandonedCart** [comment]
Ah, the infamous "ask the person standing next to you" support request.

**Comment by jumoog** [comment]
I blame it on my browser's cache :D I never saw the skip button.

**Comment by AbandonedCart** [comment]
I never have any cache on me.

**Pull request merged**
