### PR TITLE
leftEpisode and rightEpisodeIntro can be null

### PR DESCRIPTION
**Pull request by jumoog**
Uncaught (in promise) TypeError: leftEpisodeIntro is null

### CODE REVIEW

**Comment by AbandonedCart** [comment]
`Object.hasOwn()`

**Comment by jumoog** [comment]
> Does `Object.hasOwn()` exist? That would check both and simply return false.
Yes but its maybe too new.

**Comment by AbandonedCart** [comment]
Java keeps telling me how Objects is the greatest thing ever.

**Comment by jumoog** [comment]
`IntroStart` always exists

**Comment by AbandonedCart** [comment]
And you don't want to do a !== null check because it could still be undefined.

**Comment by jumoog** [comment]
Now it works.

**Pull request merged**
