### PR TITLE
Change task from being canceled to waiting

### PR DESCRIPTION
**Pull request by rlauuzo**
Tasks now wait for their turn instead of being canceled

### CODE REVIEW

**Comment by AbandonedCart** [comment]
One thing I noticed is that everything is running based on full tasks. When items are added, shouldn't we be adding them through the queue manager as the individual item. That would sidestep a lot of overlap.

**Comment by rlauuzo** [comment]
Makes sense! Is that easy to do?

**Comment by AbandonedCart** [comment]
I'm not entirely sure. My experience with C# is somewhat limited. I'm experimenting with the idea in https://github.com/jumoog/intro-skipper/pull/119, but it might give you some ideas.

**Comment by rlauuzo** [comment]
Hey, could someone please test if everything is functioning as intended? Scheduled task now properly waits for an already running task instead of immediately canceling. However, I'm unable to test the automatic tasks due Jellyfin unstable preventing me from changing the plugin settings for some reason.

**Comment by AbandonedCart** [comment]
Ah, i fixed it on 10.8 and forgot to for master

https://github.com/jumoog/intro-skipper/commit/2442e579e05a5a99abd71f0261081f41f6ce625c#diff-74a94e15e75d4263ca926b506c00750697cbed4a718b367f479a3dd7779510bfR150-R153

MaximumEpisodeCreditsDuration should be MaximumCreditsDuration. The plain text items got missed in the replace.

**Comment by AbandonedCart** [comment]
Did you want to throw it into what you're doing or do you want me to commit the change?

**Comment by rlauuzo** [comment]
I've integrated it, and it seems to be working fine now.

**Comment by AbandonedCart** [comment]
Sorry about that. I had done it in the middle of my PR and forgot all about it

**Comment by rlauuzo** [comment]
Haha, let's hope so! It does seem to be functioning as intended now.

**Comment by rlauuzo** [comment]
@AbandonedCart We still need to replace `Plugin.Instance!.AnalyzerTaskIsRunning`, but I'm uncertain if you're checking for scheduled tasks or automatic tasks. `ScheduledTaskSemaphore.CurrentCount = 0` indicates a scheduled task running, while `Entrypoint.AutomaticTaskState == TaskState.Running` signifies an automatic task.

**Comment by AbandonedCart** [comment]
A little of both. I was checking for automatic tasks to decide if it should append an item. The scheduled tasks were canceling the automatic.

**Comment by rlauuzo** [comment]
Does that imply we can also eliminate the `_analyzeAgain` logic?

**Comment by AbandonedCart** [comment]
It may be better to have a single file analyzer and keep adding items to that if it doesn't create a bottleneck.

**Pull request merged**
