### PR TITLE
select autoskip clients

### PR DESCRIPTION
**Pull request by rlauuzo**
see https://github.com/jumoog/intro-skipper/pull/274

### CODE REVIEW

**Comment by jumoog** [comment]
works perfect. maybe add some space here
grafik

**Comment by rlauuzo** [comment]
better?

**Comment by jumoog** [comment]
yes perfect

**Review by jumoog — APPROVED** [review]

**Comment by jumoog** [comment]
ship it?

**Comment by jumoog** [comment]
Okay i found a bug:
I set a client that not exists, (In the real world the session got cleaned)
grafik
but its not in the list:
grafik

**Comment by rlauuzo** [comment]
It makes an API call to retrieve all clients currently logged into the server and lists them.

**Comment by dredstone1** [comment]
The idea wasn't to have two list and the user can move the client between them?

**Comment by rlauuzo** [comment]
I'm not sure, but the drag-and-drop list doesn't work on touch devices

**Comment by dredstone1** [comment]
It's not always work on mobile, that is way I started to code a swap button between the two lists, when the user click all of the selections will swap sides, and it was very nice... But this is my opinion...

**Comment by dredstone1** [comment]
I think that you can add your fix for the saving of the list in the configuration file into #274. Because that was the main thing that was missing from #274

**Comment by AbandonedCart** [comment]
> I'm not sure, but the drag-and-drop list doesn't work on touch devices

It works but suffers from the focus issue. You have to click the item or box to shift focus and then it will let you drag when holding down. It seems like it can't take focus and register the drag in a single event.

**Pull request merged**
