### PR TITLE
Update inject.js

### PR DESCRIPTION
**Pull request by rlauuzo**

### CODE REVIEW

**Comment by jumoog** [comment]
It works, but it has too many side effects. Maybe we should try to find a way to focus the button.

**Comment by rlauuzo** [comment]
However, this will only work on TVs now.

**Comment by AbandonedCart** [comment]
That should be fine. I think the issue was mainly the awkwardness of trying to use the pointer before the button faded out again. The only other platform that would really suffer from that is Android TV, but there's a good chance the average person would use an app over the browser.

**Comment by jumoog** [comment]
wow its works very smooth on LG

**Comment by jumoog** [comment]
> That should be fine. I think the issue was mainly the awkwardness of trying to use the pointer before the button faded out again. The only other platform that would really suffer from that is Android TV, but there's a good chance the average person would use an app over the browser.

Yes, for the devices, I think everyone will use an app if there is one available.

**Comment by jumoog** [comment]
Amazon Prime Video also has no focus on the button in the browser. You have a mouse on your computer anyway. So it should work.

**Comment by jumoog** [comment]
I got some feedback: "If the intro is at the beginning, the focus disappears from the button as soon as the OSD is faded out"

**Comment by rlauuzo** [comment]
Added a check for TV/browser, so skipping with Enter should work in the browser again.

**Comment by Bretterteig** [comment]
Can you start a new build for the changes? Or can i replace the .js somewhere?

**Comment by rlauuzo** [comment]
https://github.com/rlauuzo/intro-skipper/releases/tag/10.9%2Fv0.2.0.6

**Comment by Bretterteig** [comment]
> I got some feedback from @Bretterteig "If the intro is at the beginning, the focus disappears from the button as soon as the OSD is faded out"

This issue is not resolved. 

Moreover, when the OSD fades (and the focus on the button is lost) pressing enter does not do anything anymore until a menu item is selected again (so neither skip nor pause)

**Comment by rlauuzo** [comment]
Hmm... I don't have any of those issues with this version.

**Comment by Bretterteig** [comment]
Okay, correction on my side.
On web it seems enter skips the intro but the focused status is lost (so no visual confirmation what would happen)
On TV the above still stands

**Comment by rlauuzo** [comment]
[ConfusedPolarBear.Plugin.IntroSkipper-v2.dll.zip](https://github.com/jumoog/intro-skipper/files/15393062/ConfusedPolarBear.Plugin.IntroSkipper-v2.dll.zip)
Could you test this? This time, focus should work. However, the issue with not pausing when nothing is selected while the skip button is visible remains.

**Comment by rlauuzo** [comment]
[ConfusedPolarBear.Plugin.IntroSkipper-v4.zip](https://github.com/jumoog/intro-skipper/files/15393376/ConfusedPolarBear.Plugin.IntroSkipper-v4.zip)

Or this might fix the pausing issue.

**Comment by rlauuzo** [comment]
[ConfusedPolarBear.Plugin.IntroSkipper-v6.dll.zip](https://github.com/jumoog/intro-skipper/files/15394817/ConfusedPolarBear.Plugin.IntroSkipper-v6.dll.zip)

Does this work for you?

**Comment by Bretterteig** [comment]
Button is back on web. Skip works for both TV and web. 
Two things I found:
* On web the button does not have the focused visual
* Edge case where the back button is the focused element on tv (idk... restarting the map fixed this...) I would ignore this one

**Comment by rlauuzo** [comment]
> On web the button does not have the focused visual

This is intentional since there doesn't appear to be true "focus" on desktop browsers, only hover effects.

**Pull request merged**
