### PR TITLE
Refactor BaseItemAnalyzerTask and add Edl support for credits

### PR DESCRIPTION
**Pull request by rlauuzo**
- Refactored BaseItemAnalyzerTask to use `ReadOnlyCollection<AnalysisMode>` for input.
- Added support for credits in Edl files.
- Review for the BaseItemAnalyzerTask refactor would be appreciated.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
It makes sense looking at it. You could probably drop the "intro" on the remaining analyzer names. That's really all I saw on the read through.

**Comment by AbandonedCart** [comment]
It should fix itself once it's merged to master. I tried to make as few changes to the PR as possible to not overwrite anything.

**Comment by jumoog** [comment]
sorry for conflicts

**Comment by AbandonedCart** [comment]
You may be running into the same issue I saw with the combined intro / credit task and the progress bar. You may already have this, but you either want the number of full items out of the total full items or every single scan out of the total scan processes.

**Comment by rlauuzo** [comment]
Fixed the conflicts. I believe everything should be working now.

**Comment by AbandonedCart** [comment]
Seems to be working for me. I finally got my server back up. It's been down for a couple days, so I couldn't test.

**Pull request merged**
