### PR TITLE
Use reversed fingerprints for credits

### PR DESCRIPTION
**Pull request by rlauuzo**
Use reversed fingerprints for analyzing credits. This eliminates the need for `CreditsFingerprintStart` to calculate credit timestamps, ensuring these timestamps remain unshifted even if the maximum credits duration is modified.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
I had written "in a perfect world, we could start at the end and go backwards, but it can't be that easy" and apparently never sent it. I guess I was wrong anyway.

**Comment by AbandonedCart** [comment]
I think you were on to something before, though. It may make more sense to make the user setting a suggestion and not a hard limit. Even in that rare case the credits are five minutes, we still tested 4. The only time it makes sense as a limit would be blocking chapters that aren't divided and even that can be avoided by setting a minimum number of chapters.

**Comment by rlauuzo** [comment]
I believe the value in `SamplesToSeconds = 0.128` may be inaccurate. According to this https://github.com/acoustid/notebooks/blob/master/fingerprint-matching.ipynb, the correct value should be closer to 0.1238.

**Comment by jumoog** [comment]
Nice idea! I think we can assume that each episode has about the same credit length. Maybe we can use that to speedup the process? What do guys you think?

**Comment by AbandonedCart** [comment]
> I believe the value in `SamplesToSeconds = 0.128` may be inaccurate. According to this https://github.com/acoustid/notebooks/blob/master/fingerprint-matching.ipynb, the correct value should be closer to 0.1238.

I don't know how the value was chosen originally, so it wouldn't hurt to try one with proven research

**Comment by AbandonedCart** [comment]
> Nice idea! I think we can assume that each episode has about the same credit length. Maybe we can use that to speedup the process? What do guys you think?

Hard part will be finding a balance between skipping stuff and staying accurate.

**Pull request merged**
