### PR TITLE
Allow the intro skip button to be confirmed with the Enter key

### PR DESCRIPTION
**Pull request by rlauuzo**
I've been testing this on my WebOS TV for a few days and it's been working great so far. Any suggestions or additional testing before we merge would be greatly appreciated.

### CODE REVIEW

**Review by jumoog — APPROVED** [review]

**Review by AbandonedCart — APPROVED** [review]

**Comment by jumoog** [comment]
why new commit? something wasn't working?

**Comment by AbandonedCart** [comment]
Limits the scope a little more, which is good to prevent other platforms from accidentally running it.

**Comment by Bretterteig** [comment]
Hey there, anything preventing this from beeing merged?

**Comment by jumoog** [comment]
@rlauuzo it's ready?

**Comment by rlauuzo** [comment]
Yes.

**Pull request merged**
