### PR TITLE
Ignore user selected intro duration

### PR DESCRIPTION
**Pull request by AbandonedCart**

### CODE REVIEW

**Review by jumoog — CHANGES_REQUESTED** [review]
put it in else

**Comment by jumoog** [comment]
only ignore it when config.PersistSkipButton is false?

**Comment by AbandonedCart** [comment]
The original code ignored it because the end of the intro is actually a fallback for if the user disappearance time failed

**Review by jumoog — APPROVED** [review]

**Comment by AbandonedCart** [comment]
Thanks for catching that 12. I haven't made a script to edit that automatically yet so it's copy paste

**Pull request merged**
