### PR TITLE
Enhance Chromaprint Accuracy Using Chapters

### PR DESCRIPTION
**Pull request by rlauuzo**

### CODE REVIEW

**Comment by rlauuzo** [comment]
This likely needs extended testing to ensure that everything works correctly and that no actual episode content is accidentally cut off.

**Comment by jumoog** [comment]
hmm not sure how to test this... maybe we should add a unit test?

**Review by jumoog — APPROVED** [review]

**Comment by rlauuzo** [comment]
Updates cached file suffix to `-intro-silence-v2`.

**Comment by AbandonedCart** [comment]
> Not a bad idea, but it will redo the `intro silence` analysis for every episode. Took me ~4 minutes.

How many files do you have?

**Pull request merged**
