### PR TITLE
Update Troubleshooting

### PR DESCRIPTION
**Pull request by rlauuzo**
Added troubleshooting steps for the Skip button issue for

- Hotio Docker Container
- Ubuntu/Debian
- Windows

### CODE REVIEW

**Comment by rlauuzo** [comment]
Could we remove the FFmpeg installation instructions for macOS, as version 10.9 now come with FFmpeg pre-installed?

**Comment by jumoog** [comment]
> Could we remove the FFmpeg installation instructions for macOS, as version 10.9 now come with FFmpeg pre-installed?

Good Point! Yes [Install on macOS](https://jellyfin.org/docs/general/installation/macos/)

**Comment by AbandonedCart** [comment]
Did they finally fix it? The preinstalled one was broken for a while. Either way, the instructions will still be on the 10.8 branch as a reference.

**Comment by AbandonedCart** [comment]
> Good Point! Yes [Install on macOS](https://jellyfin.org/docs/general/installation/macos/)

Not that it’s our problem, but that should be fun. The homebrew ffmpeg is a dumpster fire.

**Pull request merged**
