### PR TITLE
Fixed Skip button not displaying

### PR DESCRIPTION
**Pull request by Cloud9Developer**
Solves #104

### CODE REVIEW

**Comment by jumoog** [comment]
The url is `https://example.com:8920/Items/c96d9396d20e17431ebf5d974dfd2551/PlaybackInfo?UserId=2cdf4968f747496ca2b5cde86b4fbaf7&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&AudioStreamIndex=1&SubtitleStreamIndex=3&MediaSourceId=c96d9396d20e17431ebf5d974dfd2551&MaxStreamingBitrate=6524342`

We can extract the URL parameters. This should work more reliably.

```javascript
// URL string
const urlString = "https://example.com:8920/Items/c96d9396d20e17431ebf5d974dfd2551/PlaybackInfo?UserId=2cdf4968f747496ca2b5cde86b4fbaf7&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&AudioStreamIndex=1&SubtitleStreamIndex=3&MediaSourceId=c96d9396d20e17431ebf5d974dfd2551&MaxStreamingBitrate=6524342";

// Regular expression pattern to match MediaSourceId parameter
const regex = /[?&]MediaSourceId=([^&]+)/;

// Match the parameter in the URL string
const match = urlString.match(regex);

// Check if MediaSourceId exists
const mediaSourceIdExists = match !== null;

// If MediaSourceId exists, extract its value
let id = "";
if (mediaSourceIdExists) {
    id = match[1];
}
````

**Comment by AbandonedCart** [comment]
> https://github.com/jumoog/intro-skipper/blob/master/ConfusedPolarBear.Plugin.IntroSkipper/Configuration/inject.js#L23C7-L30C49
> 
> It's also possible the API changed, since we use an arbitrary path segment count

was also implying that's a bad idea. Even if this fixes it today, I am with @jumoog about finding a more reliable solution that will work in any situation.

**Comment by Cloud9Developer** [comment]
Yeah, I agree. It was late last night when I found it and figured I'd put a temp solution (at the very least) on the radar. But I know there are better ways to parse the url field, just don't know them off the top of my head and didn't have time last night to research.

I can refactor it later tonight if I have a chance

**Comment by AbandonedCart** [comment]
May also be good to do a `git reset --hard upstream/master` on the branch to toss out the merge commits and then `cherry-pic 
cabb245` back onto it.

**Comment by Cloud9Developer** [comment]
true, keep it clean. I thought github would have a "squash commits" option during a PR like gitlab does. Makes clean PRs with 1 commit :) guess not lol

**Comment by AbandonedCart** [comment]
It has the option, but it also lists every bit of it as the commit message.

**Comment by jumoog** [comment]
> true, keep it clean. I thought github would have a "squash commits" option during a PR like gitlab does. Makes clean PRs with 1 commit :) guess not lol

I set it to squash. But the github default is merge 🤦

**Pull request merged**
