### PR TITLE
allow the intro skip button to be confirmed with the Enter key

### PR DESCRIPTION
**Pull request by jumoog**
tested with LG webOS

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Ironically setTimeout is one of the functions that the security stuff complains about. If you add an event handler in javascript and one already exists, does it append? In java it does, but it's been a while since I had to think about "what if someone else is using enter"

**Comment by AbandonedCart** [comment]
It's probably irrelevant, but I typically target keyup because that implies it was pressed and released. Keeps it from triggering until the cat steps off the keyboard.

**Comment by jumoog** [comment]
It's irrelevant because I set [usecapture](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#usecapture) `true` for `addEventListener`.

**Comment by AbandonedCart** [comment]
> And `setTimeout` is used alot in `jellyfin-web`

The function itself is harmless. What triggers the flags is how, when, and who ran it. It's not like it really matters, given the way plugins work in general.

**Review by rlauuzo — APPROVED** [review]

**Comment by rlauuzo** [comment]
works 👍

**Pull request merged**
