### PR TITLE
Expanding user configuration

### PR DESCRIPTION
**Pull request by AbandonedCart**
Adding cache as a user setting, since it can persist between installations. I haven't quite worked out how to delete it yet (to make that part of clearing the database). I've never used Visual Studio before, so this is all new.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
The prerelease will be tagged as a prerelease in the release list. It's meant to allow downloading the zip file and manually overwriting the dll for testing.

**Comment by jumoog** [comment]
Deleting doesn't work anyway. Other plugins store their files in the media folder. But I have found that Jellyfin always keeps the files. Only if you delete the whole folder will everything be deleted.

**Comment by jumoog** [comment]
> I've never used Visual Studio before, so this is all new.

Don't worry! I know how painful it is to develop Jellyfin plugins.

**Comment by AbandonedCart** [comment]
I discovered Jellyfin a few days ago. I was using Plex, but an app I used only supported Jellyfin, so I gave it a shot.

**Comment by AbandonedCart** [comment]
I'm not sure why I was acting like this was some obscure programming language when it's just generic javascript.

**Comment by AbandonedCart** [comment]
I wanted to make sure enabling the skip button through the intro disables the entry for offsets so nobody ends up wondering why their numbers don't work.

**Comment by jumoog** [comment]
thank you 🍻

**Comment by AbandonedCart** [comment]
Of course :)

This probably doesn't need a new version yet. I want to look into the injection too.

**Pull request merged**
